# Generated by Django 4.2.7 on 2025-09-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
